name: Build and sign image
on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    name: build-image
    env:
      IMAGE_NAME: ghcr.io/shellz-n-stuff/slsa-spring-demo
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Cosign
      uses: sigstore/cosign-installer@v3.5.0

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zule'
        java-version: '17'
        cache: 'gradle'

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Gradle and Jib
      run: ./gradlew build jibDockerBuild --image=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    
    - name: Sign Docker Image with Cosign
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: |
        cosign sign --key <(echo "${{ secrets.COSIGN_KEY }}") ghcr.io/${{ github.repository }}:latest
        cosign sign --key <(echo "${{ secrets.COSIGN_KEY }}") ghcr.io/${{ github.repository }}:${{ env.COMMIT_SHA }}